### ISSUE TITLE
Getting error while trying to use injected services in the interceptor

### ISSUE THREAD

**Issue by Arvraepe** [yulonh/ng2-http-interceptor#7]
I'd like to use a Service in my interceptor

constructor(private busyService: BusyService){}

But when I try to run this code I get this really weird and ugly error:

"Error: Can't resolve all parameters for BusyInterceptor: (?).
    at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:129695:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:87175:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6982:16)
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:21347:31)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:4200/vendor.bundle.js:21222:26)
    at CompileMetadataResolver._getInjectableMetadata (http://localhost:4200/vendor.bundle.js:21210:21)
    at CompileMetadataResolver.getProviderMetadata (http://localhost:4200/vendor.bundle.js:21452:40)
    at http://localhost:4200/vendor.bundle.js:21410:49
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/vendor.bundle.js:21377:19)
    at http://localhost:4200/vendor.bundle.js:20984:63
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:20975:49)
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:60538:64)
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:60498:52)"

Is adding the constructor with an injected service not allowed?

**Comment by yulonh** [comment]
https://github.com/yulonh/ng2-http-interceptor/issues/1

**Comment by Arvraepe** [comment]
Works great!
